name: Build
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  # On master, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ (github.ref == 'refs/heads/master') && format('{0}-{1}', github.workflow_ref, github.sha) || format('{0}-{1}', github.workflow_ref, github.head_ref) }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build (amd64)
        run: |
          docker build \
            --platform amd64 \
            --tag oracle9-image:amd64 \
            .

      - name: Build (arm64)
        run: |
          docker build \
            --platform arm64 \
            --tag oracle9-image:arm64 \
            .
